import type { Metadata } from 'next'
import { Noto_Sans_SC } from 'next/font/google'
import './globals.css'

// https://fonts.google.com/noto/specimen/Noto+Sans+SC?query=Chinese%20Simplified
const simplifiedChinese = Noto_Sans_SC({ subsets: ['cyrillic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="p-10 [&_h1]:font-normal">
      <head>{/* <script src="https://cdn.tailwindcss.com"></script> */}</head>
      <body className={simplifiedChinese.className}>{children}</body>
    </html>
  )
}
